// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	users "myuseek/business/users"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetUserById provides a mock function with given fields: ctx, domain
func (_m *Repository) GetUserById(ctx context.Context, domain users.Domain) (users.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 users.Domain
	if rf, ok := ret.Get(0).(func(context.Context, users.Domain) users.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(users.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, users.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, domain
func (_m *Repository) GetUsers(ctx context.Context, domain users.Domain) ([]users.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 []users.Domain
	if rf, ok := ret.Get(0).(func(context.Context, users.Domain) []users.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, users.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *Repository) Login(ctx context.Context, email string, password string) (users.Domain, error) {
	ret := _m.Called(ctx, email, password)

	var r0 users.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string, string) users.Domain); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(users.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, firstname, lastname, username, email, password, bio, profile_pic, subscription_type
func (_m *Repository) Register(ctx context.Context, firstname string, lastname string, username string, email string, password string, bio string, profile_pic string, subscription_type string) (users.Domain, error) {
	ret := _m.Called(ctx, firstname, lastname, username, email, password, bio, profile_pic, subscription_type)

	var r0 users.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string, string) users.Domain); ok {
		r0 = rf(ctx, firstname, lastname, username, email, password, bio, profile_pic, subscription_type)
	} else {
		r0 = ret.Get(0).(users.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, firstname, lastname, username, email, password, bio, profile_pic, subscription_type)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
