name: Running Unit Test

on:
  pull_request:
    branches:
      - 'main'
  push: 
    branches:
      - 'main'

jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: running unit test
      run: go test ./... -cover
  
  build-push-docker:
    name: "Build image and push to registry"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - uses: actions/checkout@v2
    - name: build docker
      run: docker build -t adrianstanislaus/myuseek:1.0.0 .
    - name: login registry docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: push image to registry docker hub
      run: docker push adrianstanislaus/myuseek:1.0.0